### ISSUE TITLE
Bug: TA Assist crashes when trying to delete class in focus mode.

### ISSUE THREAD

**Issue by Bubbl3T** [AY2223S1-CS2103T-T12-1/tp#221] opened 2022-10-26 12:39 UTC
While this is not the intended use case, The program should not face a crash when dealing with commands this way.

**Comment by RezwanArefin01** [comment] 2022-10-26 13:01
Sound to be the same issue as in #214.

**Comment by njxue** [comment] 2022-10-26 13:30
I can't seem to reproduce this bug at my side. Did you pull the latest commit from the master branch?
Or you can try to clear all data and start with new data. I recall having weird bugs because my data was incompatible with the new storage and model implementation.

**Comment by RezwanArefin01** [comment] 2022-10-28 12:26
Fixed in #219. 

The issue was `UniqueList#remove` comparing elements by exact equality, or else throwing an exception. It was being triggered since during execution of deletec command, a new instance of `ModuleClass` is created that may not be `equals` to the one in `UniqueList`.

**Closed as completed by RezwanArefin01** 2022-10-28 12:26 UTC
Labels: type.Bug, severity.High
